((root) => {
  const refs = [
    {id:"PY-2024-01-Q1",referenceType:"past-paper",examCycle:"January 2024",questionNumber:1,title:"Past Paper + Model Answer — January 2024 Q1: Video-game platform pattern selection and Performance scenario",body:"Video-game platform pattern selection. Matching-game notifications support Publish-Subscribe when updates are pushed to interested gamers. Gamer-to-gamer resource/communication roles can support Peer-to-Peer when participants act as equal peers. Persistent progress/profile access across devices supports Client-Server with centrally managed state. A Performance quality-attribute scenario should use Source, Stimulus, Environment, Artifact, Response and a measurable Response Measure.",source:"Learning Materials/Past Year Exam Papers/CSC3209_January_2024_Answers.md",concepts:["publish-subscribe","peer-to-peer","client-server","performance","quality-attribute-scenario"]},
    {id:"PY-2024-01-Q2",referenceType:"past-paper",examCycle:"January 2024",questionNumber:2,title:"Past Paper + Model Answer — January 2024 Q2: QA scenarios, Utility Tree and notation",body:"Create scenario-specific quality requirements with the six-part QA form, then organize them in a Utility Tree using Business Value and Architectural Impact. High/High leaves are strong ASR candidates. Compare informal, semiformal and formal notation and select the required rigor based on stakeholder and analysis needs.",source:"Learning Materials/Past Year Exam Papers/CSC3209_January_2024_Answers.md",concepts:["quality-attribute-scenario","utility-tree","asr","architecture-notation"]},
    {id:"PY-2024-01-Q3",referenceType:"past-paper",examCycle:"January 2024",questionNumber:3,title:"Past Paper + Model Answer — January 2024 Q3: Service-Oriented Architecture",body:"SOA is appropriate when independently provided or consumed network services cooperate through published service interfaces/contracts. Consumers depend on contracts rather than provider internals. Discuss interoperability/modifiability benefits and network, versioning, security and intermediary trade-offs. Do not justify SOA merely because a system uses a network.",source:"Learning Materials/Past Year Exam Papers/CSC3209_January_2024_Answers.md",concepts:["soa","interoperability","modifiability","performance","security"]},
    {id:"PY-2024-01-Q4",referenceType:"past-paper",examCycle:"January 2024",questionNumber:4,title:"Past Paper + Model Answer — January 2024 Q4: Creational patterns and Observer notification",body:"Creational patterns control object-creation decisions; emphasized examples include Factory Method and Singleton. At implementation/design-pattern level, Observer is suitable when a Subject notifies registered Observers after relevant state changes. Distinguish Observer from system-level Publish-Subscribe.",source:"Learning Materials/Past Year Exam Papers/CSC3209_January_2024_Answers.md",concepts:["factory-method","singleton","observer","publish-subscribe","creational"]},

    {id:"PY-2024-08-Q1",referenceType:"past-paper",examCycle:"August 2024",questionNumber:1,title:"Past Paper + Model Answer — August 2024 Q1: myTNB pattern selection and Performance scenario",body:"Threshold notifications support Publish-Subscribe. External online-banking/card integration supports SOA when published service interfaces/contracts are consumed. Internet access to centrally managed usage/billing data supports Client-Server; Shared-Data may describe the repository mechanism when multiple accessors share one store. Explain advantages/limitations causally and write a measurable Performance scenario.",source:"Learning Materials/Past Year Exam Papers/CSC3209_August_2024_Answers.md",concepts:["publish-subscribe","soa","client-server","shared-data","performance","quality-attribute-scenario"]},
    {id:"PY-2024-08-Q2",referenceType:"past-paper",examCycle:"August 2024",questionNumber:2,title:"Past Paper + Model Answer — August 2024 Q2: QA scenarios, Utility Tree and documentation notation",body:"Write four six-part quality scenarios with objective response measures. Organize them in a Utility Tree prioritized by Business Value and Architectural Impact. Compare informal, semiformal and formal architectural notation and choose based on required precision and stakeholder needs.",source:"Learning Materials/Past Year Exam Papers/CSC3209_August_2024_Answers.md",concepts:["quality-attribute-scenario","utility-tree","architecture-notation","asr"]},
    {id:"PY-2024-08-Q3",referenceType:"past-paper",examCycle:"August 2024",questionNumber:3,title:"Past Paper + Model Answer — August 2024 Q3: Peer-to-Peer",body:"P2P uses equal peer roles: each participant may request and provide resources, with discovery and dynamic attachment supporting decentralized cooperation. Scalability can improve because peers may add capacity as well as demand. Availability improves only when equivalent resources/providers exist. Security, trust and consistency are important trade-offs.",source:"Learning Materials/Past Year Exam Papers/CSC3209_August_2024_Answers.md",concepts:["peer-to-peer","availability","security","performance"]},
    {id:"PY-2024-08-Q4",referenceType:"past-paper",examCycle:"August 2024",questionNumber:4,title:"Past Paper + Model Answer — August 2024 Q4: Behavioral design patterns and Observer",body:"Behavioral GoF patterns organize object communication and responsibility. Observer creates a one-to-many dependency so a Subject notifies registered Observers after a relevant state change. State encapsulates state-specific behavior in State objects. Distinguish implementation-level Observer from architectural Publish-Subscribe.",source:"Learning Materials/Past Year Exam Papers/CSC3209_August_2024_Answers.md",concepts:["observer","state","publish-subscribe","behavioral"]},

    {id:"PY-2025-01-Q1",referenceType:"past-paper",examCycle:"January 2025",questionNumber:1,title:"Past Paper + Model Answer — January 2025 Q1: Trading platform patterns and runtime quality attributes",body:"Multiple synchronized trading views can justify MVC; threshold stock notifications justify Publish-Subscribe; external payment providers with published interfaces justify SOA. Performance, Usability and Security can be observed at runtime, while Modifiability is primarily design/development-time. Formal runtime QA scenarios use all six scenario parts.",source:"Learning Materials/Past Year Exam Papers/CSC3209_January_2025_Answers.md",concepts:["mvc","publish-subscribe","soa","performance","usability","security","modifiability","quality-attribute-scenario"]},
    {id:"PY-2025-01-Q2",referenceType:"past-paper",examCycle:"January 2025",questionNumber:2,title:"Past Paper + Model Answer — January 2025 Q2: QA scenarios and Utility Tree",body:"Create four concrete six-part quality-attribute scenarios with quantified response measures, then place the same scenarios in a Utility Tree. Prioritize leaves by Business Value and Architectural Impact and explain why High/High leaves are architecturally significant.",source:"Learning Materials/Past Year Exam Papers/CSC3209_January_2025_Answers.md",concepts:["quality-attribute-scenario","utility-tree","asr"]},
    {id:"PY-2025-01-Q3",referenceType:"past-paper",examCycle:"January 2025",questionNumber:3,title:"Past Paper + Model Answer — January 2025 Q3: Pipe-and-Filter and pipeline parallelism",body:"Pipe-and-Filter is a C&C pattern for successive transformations of a stream. Filters independently transform input and pipes carry intermediate output. Buffered pipes allow adjacent filters to process different items concurrently, improving throughput. Extra stages add buffering/copying/synchronization overhead. Distinguish this from Map-Reduce batch partitioning.",source:"Learning Materials/Past Year Exam Papers/CSC3209_January_2025_Answers.md",concepts:["pipe-and-filter","throughput","performance","component-and-connector","map-reduce"]},
    {id:"PY-2025-01-Q4",referenceType:"past-paper",examCycle:"January 2025",questionNumber:4,title:"Past Paper + Model Answer — January 2025 Q4: Client-Server view, Layer view, cross-view mapping and Observer",body:"Document Client-Server as a runtime Component-and-Connector view and Layer as a Module view with allowed-to-use dependencies. Cross-view mapping explains how module elements implement runtime elements. Observer is suitable for implementation-level notification. Layer is logical/module organization, not physical Multi-Tier deployment.",source:"Learning Materials/Past Year Exam Papers/CSC3209_January_2025_Answers.md",concepts:["client-server","layer","component-and-connector","module-structure","cross-view-mapping","observer","multi-tier"]},

    {id:"PY-2025-08-Q1",referenceType:"past-paper",examCycle:"August 2025",questionNumber:1,title:"Past Paper + Model Answer — August 2025 Q1: Healthcare platform patterns and runtime QA measurement",body:"External mapping integration can justify SOA when an independently provided service is consumed through a published interface. Online balance/claim tracking supports Client-Server. Claim/promotion notifications support Publish-Subscribe. Availability, Performance, Usability and Security can be measured at runtime with concrete response measures.",source:"Learning Materials/Past Year Exam Papers/CSC3209_August_2025_Answers.md",concepts:["soa","client-server","publish-subscribe","availability","performance","usability","security"]},
    {id:"PY-2025-08-Q2",referenceType:"past-paper",examCycle:"August 2025",questionNumber:2,title:"Past Paper + Model Answer — August 2025 Q2: QA scenarios and Utility Tree",body:"Write four formal six-part quality scenarios for the healthcare system with testable response measures. Build a Utility Tree from the same requirements and rate each leaf by Business Value and Architectural Impact to identify the scenarios that most strongly constrain architecture.",source:"Learning Materials/Past Year Exam Papers/CSC3209_August_2025_Answers.md",concepts:["quality-attribute-scenario","utility-tree","asr"]},
    {id:"PY-2025-08-Q3",referenceType:"past-paper",examCycle:"August 2025",questionNumber:3,title:"Past Paper + Model Answer — August 2025 Q3: Model-View-Controller",body:"MVC separates application state/functionality in the Model, presentation in Views and user-input mediation in Controllers. Multiple Views may present synchronized representations of the same Model. This supports modifiability/testability, while extra structural/event-flow complexity can be a weakness.",source:"Learning Materials/Past Year Exam Papers/CSC3209_August_2025_Answers.md",concepts:["mvc","modifiability","testability","component-and-connector"]},
    {id:"PY-2025-08-Q4",referenceType:"past-paper",examCycle:"August 2025",questionNumber:4,title:"Past Paper + Model Answer — August 2025 Q4: Architecture views and view-template documentation",body:"The three major structure families are Module, Component-and-Connector and Allocation. A view is a representation of one structure. A documented view commonly includes Primary Presentation, Element Catalog, Context Diagram, Variability Guide and Rationale. For MVC, a C&C view should show Model, View and Controller runtime interactions.",source:"Learning Materials/Past Year Exam Papers/CSC3209_August_2025_Answers.md",concepts:["module-structure","component-and-connector","allocation-structure","view-documentation","mvc"]},
    {id:"PY-2025-08-Q5",referenceType:"past-paper",examCycle:"August 2025",questionNumber:5,title:"Past Paper + Model Answer — August 2025 Q5: Behavioral patterns and Observer notification",body:"Behavioral patterns address communication and responsibility among objects. For claim-approval or promotion notification at implementation level, Observer is suitable: a Subject notifies registered Observer objects through the Observer interface. Distinguish this object-level collaboration from architectural Publish-Subscribe.",source:"Learning Materials/Past Year Exam Papers/CSC3209_August_2025_Answers.md",concepts:["observer","publish-subscribe","behavioral"]},

    {id:"PY-2026-01-Q1",referenceType:"past-paper",examCycle:"January 2026",questionNumber:1,title:"Past Paper + Model Answer — January 2026 Q1: HPC QA scenarios and Utility Tree",body:"For an HPC platform, express architecturally important quality concerns as six-part scenarios with measurable response measures. Performance, Availability, Security, Usability or Interoperability may be justified by the scenario. Put the scenarios into a Utility Tree prioritized by Business Value and Architectural Impact.",source:"Learning Materials/Past Year Exam Papers/CSC3209_January_2026_Answers.md",concepts:["quality-attribute-scenario","performance","availability","security","utility-tree","asr"]},
    {id:"PY-2026-01-Q2",referenceType:"past-paper",examCycle:"January 2026",questionNumber:2,title:"Past Paper + Model Answer — January 2026 Q2: HPC pattern selection and runtime qualities",body:"Task-completion notifications support Publish-Subscribe when completion events are pushed. Online task/data tracking supports Client-Server when users request centrally managed information. Payment/plan integration can justify SOA when independently provided payment services expose published interfaces/contracts. Explain QA benefits/trade-offs and measurable runtime qualities.",source:"Learning Materials/Past Year Exam Papers/CSC3209_January_2026_Answers.md",concepts:["publish-subscribe","client-server","soa","availability","performance","usability","security"]},
    {id:"PY-2026-01-Q3",referenceType:"past-paper",examCycle:"January 2026",questionNumber:3,title:"Past Paper + Model Answer — January 2026 Q3: Map-Reduce parallel processing",body:"Map-Reduce is suitable for enormous batch datasets because input is partitioned across Map tasks, intermediate key/value data is shuffled/sorted, and Reduce tasks combine results. Parallel execution can improve batch throughput/scalability. Weaknesses include small-job overhead, data skew/stragglers, shuffle cost and complexity for dependent workflows.",source:"Learning Materials/Past Year Exam Papers/CSC3209_January_2026_Answers.md",concepts:["map-reduce","performance","throughput","allocation-structure","pipe-and-filter"]},
    {id:"PY-2026-01-Q4",referenceType:"past-paper",examCycle:"January 2026",questionNumber:4,title:"Past Paper + Model Answer — January 2026 Q4: Notations, architecture views and view template",body:"Compare informal, semiformal and formal architecture notation. Major structure/view families are Module, Component-and-Connector and Allocation. A view-template answer should explain Primary Presentation, Element Catalog, Context Diagram, Variability Guide and Rationale. For Map-Reduce, an allocation-oriented view can show tasks/data partitions mapped to computational nodes.",source:"Learning Materials/Past Year Exam Papers/CSC3209_January_2026_Answers.md",concepts:["architecture-notation","module-structure","component-and-connector","allocation-structure","view-documentation","map-reduce"]}
  ];

  root.PAST_PAPER_REFERENCES = refs;
  const existing = root.UNIVERSAL_REFERENCES || [];
  const seen = new Set(existing.map(r => r.id));
  const additions = refs.filter(r => !seen.has(r.id));
  if (additions.length) root.UNIVERSAL_REFERENCES = [...existing, ...additions];
  if (typeof module !== "undefined") module.exports = refs;
})(typeof window !== "undefined" ? window : globalThis);
